baseURL = 'https://dresdene.github.io/'
DefaultContentLanguage = 'zh'
languageCode = 'zh-cn'
title = 'DresdenE的巢穴'
theme = 'diary'

[params]
  disableToC = true

[taxonomies]
  category = "categories"

[[menu.main]]
url = "/posts"
name = "时间线"
weight = 1
[[menu.main]]
url = "/about"
name = "碎碎念"
weight = 2
[[menu.main]]
url = "/categories"
name = "房间"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 4